name: Deploy PROD
on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        env:
          VITE_COGNITO_DOMAIN: https://user.testigoelectoral.org
          VITE_COGNITO_CLIENT_ID: 715casirs9gvlbu88sc2rtvqf8
        run: |
          env|grep "^VITE_" > .env
          npm run build
      - name: Publish APP
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_PROD }}
          AWS_REGION: "us-east-2"
          BUCKET: "testigoelectoral-webapp-prod"
        run: |
          aws s3 sync build/ s3://${BUCKET}
