name: Deploy PROD
on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        env:
          VITE_COGNITO_DOMAIN: https://user.testigoelectoral.org
          VITE_COGNITO_CLIENT_ID: 3g6thcqri4ke4okkkhn3rpctj2
        run: |
          env|grep "^VITE_" > .env
          npm run build
      - name: Publish APP
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_PROD }}
          AWS_REGION: "us-east-2"
          BUCKET: "testigoelectoral-webapp-prod"
        run: |
          find build -type f -exec gzip -9 {} \; -exec mv {}.gz {} \;
          aws s3 sync --delete --acl public-read --content-encoding gzip build/ s3://${BUCKET}
      - name: Invalidate cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_PROD }}
          AWS_REGION: "us-east-2"
          CLOUDFRONT_ID: "E1QEV7TGARVDS5"
        run: |
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --path "/*"
